/**
 * The photo registry. Source photographs live in images/pathwayswithin-images
 * (the export of the old Squarespace site, grouped by old page). Nothing in
 * the app reads that folder: scripts/build-images.mts cuts WebP tiers from it
 * into public/images and writes lib/images/generated.json with the intrinsic
 * size of every tier, and the components read only that.
 *
 * One group file per page family under lib/images/groups. A group owns its
 * assets and the pages it decorates, so the families can be curated in
 * parallel without touching one shared file.
 */

/** Where the photograph's subject sits, for object-position on a cover crop. */
export type Focal =
  | "center"
  | "top"
  | "bottom"
  | "left"
  | "right"
  | "top left"
  | "top right"
  | "bottom left"
  | "bottom right"
  | `${number}% ${number}%`;

export interface AssetSource {
  /** Stable id, kebab case, unique across every group. Becomes the file stem. */
  id: string;
  /** Path relative to images/pathwayswithin-images, e.g. "home/unsplash-image-4GN3kBR7IMY.jpg". */
  file: string;
  /**
   * Cut a square from the source (headshots and anything shown in a circle).
   * "attention" finds the busiest region, usually a face; "top" keeps the top.
   */
  square?: "attention" | "top" | "center";
}

export interface Photo {
  /** AssetSource.id */
  asset: string;
  /** Accessible description. Decorative photographs pass "" and are skipped by readers. */
  alt: string;
  focal?: Focal;
}

/** How a section photograph sits relative to its copy. */
export type SectionPhotoLayout = "split" | "band" | "feature";

export interface SectionPhoto extends Photo {
  /** Circle for a person or a room (design rule); rounded for everything else. */
  shape?: "rounded" | "circle";
  /**
   * Crop of a rounded figure on wide viewports. Portrait (4:5) suits a long
   * section and a portrait source; landscape (4:3) suits a wide source or a
   * short section. Ignored for circles.
   */
  aspect?: "portrait" | "landscape" | "square";
  /** Which side of the copy the photograph takes on wide viewports. */
  side?: "start" | "end";
  /**
   * Placement inside the section card. `split` (default) is copy + figure side
   * by side; `feature` enlarges the media column; `band` is a full-bleed
   * horizontal photograph with copy above or below (never overlaid).
   */
  layout?: SectionPhotoLayout;
}

/**
 * One photograph, or several for denser pages. The first entry is the primary
 * figure (split / feature / band beside or under the copy); further entries
 * with `layout: "band"` render as extra full-width media after that figure.
 */
export type SectionPhotos = SectionPhoto | SectionPhoto[];

export interface PagePhotos {
  /** Editorial band directly under the opening lockup. Also the og:image. */
  hero?: Photo;
  /** Keyed by the section's h2 id (the slug of the heading text). */
  sections?: Record<string, SectionPhotos>;
  /** Resolves `[IMAGE: alt]` markers that carry no src, in document order. */
  inline?: Photo[];
}

export interface ImageGroup {
  /** Human name, for the build report. */
  name: string;
  assets: AssetSource[];
  /** Keyed by page url, e.g. "/therapy/emdr". */
  pages: Record<string, PagePhotos>;
}

/** Headshot rows for lib/images/groups/providers.ts. */
export interface HeadshotSource {
  /** providers-sheet.csv slug */
  slug: string;
  /** Path relative to images/pathwayswithin-images */
  file: string;
  square?: AssetSource["square"];
}

/* Generated by scripts/build-images.mts. */

export interface GeneratedTier {
  width: number;
  height: number;
  /** Public path, e.g. /images/photos/emdr-window-1280.webp */
  src: string;
}

export interface GeneratedAsset {
  id: string;
  /** Intrinsic size of the largest tier. */
  width: number;
  height: number;
  /** "full" or the square strategy the tiers were cut with; a change forces a recut. */
  crop?: string;
  tiers: GeneratedTier[];
}

export interface GeneratedManifest {
  builtAt: string;
  photos: Record<string, GeneratedAsset>;
  /** Keyed by provider slug. */
  headshots: Record<string, GeneratedAsset>;
}
